parameters:
#    ayman_blog.example.class: ayman\BlogBundle\Example

services:
#    ayman_blog.example:
#        class: %ayman_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    blog_ayman.antispam:
        class: ayman\BlogBundle\Antispam\BlogAntispam